language: java

install: true

jdk:
  - oraclejdk7

script:
  - gradle clean build
  - gradle dist

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/ArekCzarnik/RxJavaString --tags
  - ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: [redacted]
  file:
    - "dist/rxjava-string-1.0.1-SNAPSHOT.jar"
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/

env:
  global:
    secure: [redacted]